wekan:
  image: mquandalle/wekan
  restart: always
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://${WEKAN_HOST}:${WEKAN_PORT}
    - MAIL_URL=smtp://mailhost.der.edf.fr:25/
    - MAIL_FROM=wekan-admin
  ports:
    - ${WEKAN_PORT}:80

wekandb:
   image: mongo
   restart: always
   volumes:
     - ${WEKAN_HOME}:/data/db
