version: '2'

services:

  storage:
    image: busybox
    volumes:
      - ${REGISTRY_STORAGE_PATH}:/var/lib/registry

  backend:
    image: "registry:2"
    restart: always
    ports:
      - "${REGISTRY_BACKEND_PORT}:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    volumes_from:
      - storage

  frontend:
    image: "konradkleine/docker-registry-frontend:v2"
    restart: always
    ports:
      - "${REGISTRY_FRONTEND_PORT}:80"
    links:
      - backend
    environment:
      ENV_DOCKER_REGISTRY_HOST: backend
      ENV_DOCKER_REGISTRY_PORT: ${REGISTRY_BACKEND_PORT}
